### PR TITLE
Fix assumption that sys/sysmacros.h is included.

### PR DESCRIPTION
**Pull request by R030t1**
See https://sourceware.org/ml/libc-alpha/2015-11/msg00253.html.

### CODE REVIEW

**Comment by pszewczyk** [comment]
I think it could be done in single commit and also include description of the problem in commit message, not only in this pull request.

**Comment by R030t1** [comment]
What do you want in the description? If you'd like it can be added when you merge. If you really won't merge the changes unless I redo the branch I made I suppose I will redo it, but I don't see the point in curating git commits. If the commits don't reflect the actual development process then what is the point?

I made so many commits to make sure I didn't add the directive in places it wasn't needed.

**Comment by kopasiak** [comment]
Commit should reflect the actual development but the should be meaningful not just a single line of code. Please squash them all together and write a good commit message that clarifies why you are doing it (please remember to provide the link from pull request message as it's great source)

**Comment by kopasiak** [comment]
Merged in #29

**Pull request closed without merging**
