### PR TITLE
Os descriptors upstreaming v3

### PR DESCRIPTION
**Pull request by falstaff84**
Hi Krzysztof,

Version 3, now using interface name as parameter.

Best regards,
Stefan

--
Notes from previous versions:
Finally came around to rebase/retest my work on OS descriptors support. This needs a kernel 4.13 or newer to properly support gadget-export due to two issue:
https://patchwork.kernel.org/patch/9548869/

Both have been accepted and especially the first fix makes life of libusbgx much easier, since UTF-16 to UTF-16 conversion would have added iconv as a dependencies...

### CODE REVIEW

**Comment by falstaff84** [comment]
@kopasiak friendly reminder on that one.

**Comment by kopasiak** [comment]
@falstaff84 
This is just a note to let you now that I'm working on this. I found couple of problems in this series and I'm fixing them. I'll try to post the update shortly.

Sorry for the delay. I'm really embarrassed that it takes so long. I had a lot of work recently and other stuff including sickness leave and holidays. I hope to merge this in this week.

**Comment by kopasiak** [comment]
@falstaff84 
Finally I managed to get through this. I fixed couple of issues and changed convention here and there. I also added some example how to use this new API. Please take a look at #17 and let me know if it works for you

**Comment by kopasiak** [comment]
v4 has been already merged so I'm closing this one. Thanks.

**Pull request closed without merging**
