### PR TITLE
Adds LibUsbgxConfig.cmake to help cmake find and import the library

### PR DESCRIPTION
**Pull request by studiofuga**
This allows cmake's users to do a 

```
find_package(LibUsbgx)
target_link_library(... LibUsbgx::LibUsbgx)
```

and automatically compile and link with usbgx

### CODE REVIEW

**Comment by studiofuga** [comment]
Added a patch fixing an issue when cross-compiling.

**Comment by kopasiak** [comment]
What's the current status of this change? If it;s ready how about squashing your commits?

**Comment by studiofuga** [comment]
At the moment, I'm using this set of changes in my project and found no issues so far.
So I guess yes, they can be squashed and merged. Sorry, I don't know how to squash those commits on my side,  that are already pushed on my master branch..

**Comment by studiofuga** [comment]
I remade the pull request from a different branch, so this can be closed.

**Pull request closed without merging**
